data_dir : "./data"
layer_num: None
batch_size: 5
num_workers: 4
DEBUG: False
seed: 42

optimizer: "SGD"
learning_rate: 0.0001
weight_decay: 0.01
criterion: "kl"

start_factor: 1.
end_factor: 0.0
total_iters: 250

#max_epochs: 100
gradient_clip_val: 1.0
accumulate_grad_batches: 12
